name: work-1
on:
  push:
    paths: # 아래 파일 중 하나가 변경되어야 작동
      - '.github/workflows/**'
      - 'src/**'
      - 'build.gradle'
      - 'build.gradle.kts'
      - 'Dockerfile'
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      # 코드 가져오기
      - uses: actions/checkout@v4 
      # 태그 생성
      - name: Create Tag 
        id: create_tag # outputs(new_tag, changelog 등)
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # 릴리즈 생성
      - name: Create Release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }} # 전 단계(id: create_tag)에서 생성된 new_tag
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false